---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pod-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: /storage-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pod-pvc
spec:
  volumeName: pod-pv
  volumeMode: Filesystem
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-exchange-pvc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: busybox-multitool-pvc
  template:
    metadata:
      labels:
        app: busybox-multitool-pvc
    spec:
      containers:
      - name: busybox
        image: busybox
        command: ["/bin/sh", "-c"] 
        args: ["while true; do echo $(date) > /storage/text.txt; sleep 5; done"]
        volumeMounts:
        - name: pod-pv-vol
          mountPath: /storage
      - name: multitool
        image: wbitt/network-multitool:latest
        command: ["/bin/sh", "-c"]
        args: ["until [ -f /logs/text.txt ]; do sleep 1; done; tail -f /logs/text.txt"]
        volumeMounts:
        - name: pod-pv-vol
          mountPath: /logs
      volumes:
      - name: pod-pv-vol
        persistentVolumeClaim:
          claimName: pod-pvc
