# apiVersion: storage.k8s.io/v1
# kind: StorageClass
# metadata:
#   name: my-storage
# provisioner: kubernetes.io/no-provisioner # ИНФОРМАЦИЯ: Нет автоматического развёртывания
# volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pod-sc
spec:
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-exchange-sc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: busybox-multitool-sc
  template:
    metadata:
      labels:
        app: busybox-multitool-sc
    spec:
      containers:
      - name: busybox
        image: busybox
        command: ["/bin/sh", "-c"] 
        args: ["while true; do echo $(date) > /storage/text.txt; sleep 5; done"]
        volumeMounts:
        - name: pod-sc-vol
          mountPath: /storage
      - name: multitool
        image: wbitt/network-multitool:latest
        command: ["/bin/sh", "-c"]
        args: ["until [ -f /logs/text.txt ]; do sleep 1; done; tail -f /logs/text.txt"]
        volumeMounts:
        - name: pod-sc-vol
          mountPath: /logs
      volumes:
      - name: pod-sc-vol
        persistentVolumeClaim:
          claimName: pod-sc
